name: 'Build Mac'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # run every saturday at 4:41 AM
    - cron: '41 4 * * SAT'
  workflow_dispatch:
jobs:
  # 64-bit osx
  build-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install scons sdl2 sdl2_image sdl2_mixer sdl2_ttf glew glm curl
    - run: scons build-dir="out" -j 8 architecture=x64
    - run: python3 etc/meta/assemble-release.py . opengml-release out

    # run tests
    - run: chmod a+x opengml-release/ogm-test
    - run: chmod a+x opengml-release/ogm
    - run: opengml-release/ogm-test

    - uses: actions/upload-artifact@v2
      with:
        name: opengml-osx-x86_64
        path: opengml-release/
