name: 'Build Windows'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # run every saturday at 4:41 AM
    - cron: '41 4 * * SAT'
  workflow_dispatch:
jobs:
  # 32-bit windows build
  build-win32:
    runs-on: windows-latest
    steps:

    # pull
    - uses: actions/checkout@v2

    # for debugging
    - run: python3 etc/meta/print-env.py

    # download dependencies
    - name: get-scons
      run: python3 -m pip install scons
    - name: get-vcpkg
      run: git clone --single-branch --depth 1 -b 2019.10 --recurse https://github.com/Microsoft/vcpkg
    - uses: lukka/run-vcpkg@main
      with:
        vcpkgArguments: "sdl2 sdl2-image sdl2-mixer sdl2-ttf glew glm curl freeglut"
        vcpkgTriplet: "x86-windows"
        vcpkgGitCommitId: "6282cab61d175974b1af06473db584b9b80dcd48"
        vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
    - run: vcpkg integrate install

    # build
    - run: scons build-dir="out" release=1 -j 8 architecture=x86 --debug=findlibs
      env:
        LD_LIBRARY_PATH: '${{ runner.workspace }}/vcpkg/installed/x86-windows/lib'
        CPATH: '${{ runner.workspace }}/vcpkg/installed/x86-windows/include'
        MSVC_USE_SCRIPT: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars32.bat"
        SCONS_MSCOMMON_DEBUG: '-'
    - run: python3 etc/meta/assemble-release.py . opengml-release out

    # release
    - uses: actions/upload-artifact@v2
      with:
        name: opengml-win-x86
        path: opengml-release/

